### ISSUE TITLE
Encountered invalid prevhash error

### ISSUE THREAD

**Issue by splawik21** [dashpay/electrum-dash-old#104]
Using account nr 2 and want to send the masternode earning to another address inside the account or/and outside but always getting the same error.
Tried to send from other addresses where there is ONLY 1 input and there is no problem to do it. Where there are at least 2 inputs on the same address then the error occurs.
What I`ve noticed as well is that when I remove the 2 input from this address the tx is going to be signed, when instead I remove the 1 input in the address and want to send the second one the error occours.

Tried with another address and the same issue appears.
Tried sending from other account nr 1 and the same error occours.

The problem is when you want to spend the inuts from the address after the first input is made of 1000 coins - these stay as the masternodes.

Electrum version: 2.6.4 + trezor
Sending the screen:

![electrum - encountered invalid prevhash](https://cloud.githubusercontent.com/assets/14001049/24588664/08925eb6-17cd-11e7-9c54-8598bd2207bf.jpg)

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
