### ISSUE TITLE
Ubuntu 16.04 'install' issue

### ISSUE THREAD

**Issue by Voluntary-zcash** [dashpay/electrum-dash-old#106]
Download the archive from electrum-dash.org (where there are no install instructions), un-archive, open terminal, enter "./electrum-dash" and get this:

Error: No module named dns. Try 'sudo pip install <module-name>'

So I enter "sudo pip install dns"...  

The directory '/home/zec/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/zec/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Welcome to the 21st century.  ffs...

**Comment by nmarley** [comment]
Hi,

Thanks for reporting. Please remember that this was a voluntary, open-source effort. Your tone is borderline unacceptable. Feel free to contribute fixes in the form of PRs.

The current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you continue to have issues.
