### ISSUE TITLE
error: The transaction was rejected by network rules.(64: dust)

### ISSUE THREAD

**Issue by vikulin** [dashpay/electrum-dash-old#80]
Used Electrum wallet 2.4.1 under Ubuntu 16 x86_64.
https://i.imgsafe.org/51d7c501ae.png
As result when I send 0.075 DASH to the XdPjfH6U24E9ugJZK8nk6BQvPvS7A9JmS1 I'm seeing the following error:
https://i.imgsafe.org/51d575adef.png

**Comment by schinzelh** [comment]
May i ask you to try Electrum-Dash 2.6.4 --> https://github.com/dashpay/electrum-dash/tree/develop and try to reproduce the error?

**Comment by vikulin** [comment]
There is no reason to reproduce the issue on 2.6.4: The issue did not reproduce when I sent smaller amount. Conclusion: that is an GUI message issue.

**Comment by Kefkius** [comment]
Changes since 2.4.1 include canonical tx signature encoding, which could possibly be the problem here. That would explain why the error is not reproducible every time.

**Comment by vikulin** [comment]
That is definitely related to transaction amount: when I put smaller amount the transaction passed as well.

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
