### ISSUE TITLE
fix of hid-api on mac with new Trezor firmware

### ISSUE THREAD

**Issue by karel-3d** [dashpay/electrum-dash-old#81]
Hello,

we made a fix of hid-api in order for Trezor with new firmware to work on mac with python

https://pypi.python.org/pypi/hidapi/0.7.99.post18

(we are using our fork of hid-api C library, since the PR is stuck on signal11 github now - https://github.com/signal11/hidapi/pull/288 , https://github.com/signal11/hidapi/pull/40 )

Anyway, I don't understand electrum-dash mac build system well enough, so I am not sure what is needed to be done so that electrum mac binary is using new hidapi library (trezor plugin is using python-trezor, and that has hidapi as a dependency).

**Comment by schinzelh** [comment]
Many thanks, i'll have a look at it - waiting for my new MacBook to arrive :-)

**Comment by runn1ng** [comment]
Note that the issue is relevant *only* with mac and *only* with new firmware - it was triggered by U2F functionality.

**Comment by runn1ng** [comment]
I *think* adding `hidapi==0.7.99.post18` to `requirements.txt` should ensure that new hidapi is used

**Comment by runn1ng** [comment]
Hello, how does it look like? Is it fixed now? (I cannot test it, I doesn't have a mac :))

**Comment by schinzelh** [comment]
I'll have a look at it today

**Comment by koalalorenzo** [comment]
What is the status of this? I am not able to use Dash ATM :( 
Any update?

**Comment by goodc0re** [comment]
Yes, whats the status? My DASH are still inaccessible with Trezor / Electrum DASH

**Comment by koalalorenzo** [comment]
@schinzelh @runn1ng Any news? This should have high priority since is not allowing us to use our dash.

**Comment by rube563** [comment]
I have my DASH stuck with Trezor/Electrum Wallet as well, can use it just in view mode only, not able to move any coin. PLEASE take a look at this... BIG problem for DASH. It shouldn't be happening.

**Comment by rubenskinjo** [comment]
hope this year I'm be able to use my dash.

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
