### ISSUE TITLE
Address window - History table does not expand with resize

### ISSUE THREAD

**Issue by kryztoval** [dashpay/electrum-dash-old#90]
When you open a history window from the addresses tab and resize the new window, the control for the history does not resize itself.

![image](https://cloud.githubusercontent.com/assets/5733028/22856426/cc652650-f056-11e6-8c22-c74709cbfbb9.png)

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
