### ISSUE TITLE
koki1

### ISSUE THREAD

**Issue by koki1** [dashpay/electrum-dash-old#92]
Can't send transactions because it shows an error: "Your client produced a transaction that is not accepted by the network any more. Please upgrade to Electrum 2.5.1 or newer".

But I can't find Electrum-DASH 2.5.1 version...

**Comment by thelazier** [comment]
There is Electrum-Dash 2.6.4 on branch `develop` which is not released.
The latest compiled version for windows could be found at https://dashpay.atlassian.net/builds/browse/ELMW-DEV-120/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
