### ISSUE TITLE
unconfirmed transactions

### ISSUE THREAD

**Issue by tokerato** [dashpay/electrum-dash-old#98]
I was using electrum-dash 2.4.1 and could not send transactions using ubuntu 16.04. 

I then followed instructions to upgrade to the latest version. I sent 0.2 dash successfully and followed that transaction up by sending a much larger amount that is now stuck in an unconfirmed status.

Block explorer is not showing the transaction ID either.

Please help!

**Comment by thelazier** [comment]
Please let us know if this solution works with your situation https://github.com/dashpay/electrum-dash/issues/95#issuecomment-281944464 , or explain more about your situation, ex: which instruction? what OS?

**Comment by tokerato** [comment]
Hi thelazier. Appreciate your attention on this issue but I'm not sure what other information I can provide.

I was sending Dash from address a to address b and it's stuck in an unconfirmed state in my electrum-dash and my coins are unavailable to me and the transaction ID is not showing up on the blockexplorer.

As per my first comment I am on ubuntu 16.04.

I raised a thread on reddit about this and it looks like I'm not the only one impacted:

https://www.reddit.com/r/dashpay/comments/5x6hhp/electrumdash_unconfirmed_transaction/

The solution you provided is for Windows.

**Comment by thelazier** [comment]
Another solution , you can export private keys from electrum-dash into csv file and import them one by one into Dash Core via "importprivkey" command (you don't have to import every single key btw, just import the ones which are holding some funds).

I hope the team will release a working version soon.

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
